### PR TITLE
Picking latest solidity version from the given interval

### LINKED ISSUE #12: Correctly pick a Solidity version from the specified interval
*Description*

Consider this contract

```solidity
pragma solidity >=0.4.20 <0.4.22;

contract A {}
```

Running mythos will not correctly identify the Solidity version and will pick latest which will fail at compilation time

```sh-session
$ mythos analyze ./a.sol A                                                                 
Reading contract ./a.sol... done
Downloading Solidity version latest
./a.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.5+commit.47a71e8f.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
contract A {}
^------^

Compiling contract ./a.sol... failed
```

*Remediation*

Pick the correct Solidity version when an interval is specified.

### PR DESCRIPTION
**Pull request by nanspro**
Fixes #12

### CODE REVIEW

**Comment by b-mueller** [comment]
@cleanunicorn apparently something is wrong with the CI setup?

**Comment by nanspro** [comment]
Yeah i just updated the PR to fix lint errors but it is still showing the same

**Comment by cleanunicorn** [comment]
@nanspro I just tested it and it doesn't work with all versions.

I think these should be supported but also any others that are valid in Solidity.

I've added some examples it should work with:
```solidity
pragma solidity >=0.4.24; // Should be 0.4.24
pragma solidity >0.4.24; // Should be latest
pragma solidity >0.4.20 <0.5.0; // Should be 0.4.25
pragma solidity >=0.4.20 <=0.5.0; // Should be 0.5.0
pragma solidity >0.4.20 <=0.5.0; // Should be 0.5.0
pragma solidity <0.5.0; // Should be 0.4.25
pragma solidity <=0.5.0; // Should be 0.5.0
```

**Comment by nanspro** [comment]
@cleanunicorn  ahh yes there was a small mistake. fixed and tested it on all the above examples

**Pull request merged**
